# Generated by Django 5.1.2 on 2024-11-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='transaction',
        ),
    ]
