# Generated by Django 5.1.2 on 2024-10-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='category_type',
        ),
    ]
