# Generated by Django 5.1.2 on 2024-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_transaction_type_transaction_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcategory',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenses', 'Expenses')], max_length=255),
        ),
    ]
