# Generated by Django 5.1.2 on 2024-10-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_allcategory_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
